name: HacknCore
version: '0.1.1'
main: org.darkbriks.hacknCore.HacknCore
api-version: '1.21'
authors: [ Darkbriks ]
website: https://github.com/Darkbriks/Hack-n-Core

commands:
  get-item-permission:
    description: "Get the permission required to use an item."
    usage: /get-item-permission [item]
    permission: HacknCore.permission.see
    permission-message: "You do not have permission to see the permission of items."

permissions:
  HacknCore.permission.see:
    description: "Allows the player to see the permission required to use an item."
    default: true